
development:
  adapter: postgresql
  encoding: unicode
  database: todolist_development
  pool: 5
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: todolist_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: todolist_production
  pool: 5
  username: postgres
  password: